// <auto-generated />
using DealerDatabase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DealerDatabase.Data.Migrations
{
    [DbContext(typeof(DealerDbContext))]
    [Migration("20261006190002_newTables")]
    partial class newTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DealerDatabase.Data.Entities.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressSource")
                        .HasColumnType("TEXT");

                    b.Property<int>("AvgDaysInStock")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgListedPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FcaFrn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FcaStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("FcaStatusEffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FranchiseMake")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GoogleRating")
                        .HasColumnType("TEXT");

                    b.Property<int>("GoogleReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IcoExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IcoRegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncorporationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SafExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SafStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerType")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoldLast30Days")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StockFeedProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Town")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TrustpilotScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarrantyOffered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsitePlatform")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerFcaPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealerId", "Permission")
                        .IsUnique();

                    b.ToTable("DealerFcaPermissions");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerOfficer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppointedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealerId", "Name")
                        .IsUnique();

                    b.ToTable("DealerOfficers");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerSicCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DealerId", "Code")
                        .IsUnique();

                    b.ToTable("DealerSicCodes");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerFcaPermission", b =>
                {
                    b.HasOne("DealerDatabase.Data.Entities.Dealer", "Dealer")
                        .WithMany("FcaPermissions")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerOfficer", b =>
                {
                    b.HasOne("DealerDatabase.Data.Entities.Dealer", "Dealer")
                        .WithMany("Officers")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerSicCode", b =>
                {
                    b.HasOne("DealerDatabase.Data.Entities.Dealer", "Dealer")
                        .WithMany("SicCodes")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.Dealer", b =>
                {
                    b.Navigation("FcaPermissions");

                    b.Navigation("Officers");

                    b.Navigation("SicCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
